### ISSUE TITLE
Docker-compose SocketIo problem

### ISSUE THREAD

**Issue by amonyphily** [d3vzer0/reternal-quickstart#8]
Hello,

I would like to install Reternal from docker-compose file. The processus failed because of this error.  Can you help me please ? 

Thank you
```
api-socket_1     | Traceback (most recent call last):
api-socket_1     |   File "/usr/local/bin/celery", line 10, in <module>
api-socket_1     |     sys.exit(main())
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/celery/__main__.py", line 16, in main
api-socket_1     |     _main()
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 322, in main
api-socket_1     |     cmd.execute_from_commandline(argv)
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/celery.py", line 496, in execute_from_commandline
api-socket_1     |     super(CeleryCommand, self).execute_from_commandline(argv)))
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 288, in execute_from_commandline
api-socket_1     |     argv = self.setup_app_from_commandline(argv)
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 502, in setup_app_from_commandline
api-socket_1     |     self.app = self.find_app(app)
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 524, in find_app
api-socket_1     |     return find_app(app, symbol_by_name=self.symbol_by_name)
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/celery/app/utils.py", line 368, in find_app
api-socket_1     |     sym = symbol_by_name(app, imp=imp)
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/celery/bin/base.py", line 527, in symbol_by_name
api-socket_1     |     return imports.symbol_by_name(name, imp=imp)
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/kombu/utils/imports.py", line 57, in symbol_by_name
api-socket_1     |     module = imp(module_name, package=package, **kwargs)
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/celery/utils/imports.py", line 111, in import_from_cwd
api-socket_1     |     return imp(module, package=package)
api-socket_1     |   File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
api-socket_1     |     return _bootstrap._gcd_import(name[level:], package, level)
api-socket_1     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
api-socket_1     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
api-socket_1     |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
api-socket_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
api-socket_1     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
api-socket_1     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
api-socket_1     |   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
api-socket_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
api-socket_1     |   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
api-socket_1     |   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
api-socket_1     |   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
api-socket_1     |   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
api-socket_1     |   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
api-socket_1     |   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
api-socket_1     |   File "/reternal-backend/app/__init__.py", line 7, in <module>
api-socket_1     |     from flask_socketio import SocketIO
api-socket_1     |   File "/usr/local/lib/python3.6/site-packages/flask_socketio/__init__.py", line 22, in <module>
api-socket_1     |     from socketio.exceptions import ConnectionRefusedError
api-socket_1     | ImportError: cannot import name 'ConnectionRefusedError'
```

**Comment by d3vzer0** [comment]
Hiya :) The docker-compose file is a bit outdated and replaced in favor of the Ansible Playbook. Did you check out the Ansible installation manual as well? :)

**Comment by amonyphily** [comment]
Thank you for your response !
I fixed this issue by modifying the requirements  in /backend and /c2 :
python-socketio (without specifying a version)
 :)
